name: Production environment infrastructure deployment

on:
    push:
        paths:
            - "infra/production/**"
        branches:
            - main

    workflow_dispatch:

    workflow_call:

defaults:
    run:
        working-directory: ./infra/production

jobs:
    staging_infra_deploy:
        runs-on: ubuntu-latest
        environment:
            name: production

        env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

        steps:
            - name: Checkout repository
              uses: actions/checkout@v5

            - name: Setup terraform
              uses: hashicorp/setup-terraform@v3
              with:
                  cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

            - name: Terraform Init
              run: terraform init

            - name: Terraform validate
              run: terraform validate

            - name: Terraform plan
              id: plan
              run: terraform plan

            - name: Terraform apply
              run: terraform apply -auto-approve
