name: Staging infra CI

on:
    pull_request:
        paths:
            - "infra/staging/**"
        branches:
            - main

defaults:
    run:
        working-directory: ./infra/staging

jobs:
    staging_infra_validation_and_plan:
        runs-on: ubuntu-latest
        environment:
            name: staging

        env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

        steps:
            - name: Checkout repository
              uses: actions/checkout@v5

            - name: Setup terraform
              uses: hashicorp/setup-terraform@v3
              with:
                  cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

            - name: Terraform Init
              run: terraform init

            - name: Terraform validate
              run: terraform validate

            - name: Terraform plan
              id: plan
              run: terraform plan

            - name: Post Terraform plan to PR
              if: github.event.pull_request.merged == false && github.event.pull_request.state == 'open'
              uses: actions/github-script@v8
              with:
                  script: |
                      const message = `
                      ### Terraform Plan


                      \`\`\`
                      ${{ steps.plan.outputs.stdout }}
                      \`\`\`
                      `

                      github.rest.issues.createComment({
                          issue_number: context.issue.number,
                          owner: context.repo.owner,
                          repo: context.repo.repo,
                          body: message
                      })
